# Generated by Django 5.0.6 on 2024-07-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="detailuser",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
    ]
