# Generated by Django 5.0.6 on 2024-07-02 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_detailuser_ativo"),
        ("roles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="detailuser",
            name="role",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="roles.role"
            ),
            preserve_default=False,
        ),
    ]
