# Generated by Django 5.0.6 on 2024-07-02 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_detailuser_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detailuser",
            name="role",
        ),
        migrations.RemoveField(
            model_name="detailuser",
            name="status",
        ),
    ]
