# Generated by Django 5.0.6 on 2024-07-02 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_detailuser_role_remove_detailuser_status"),
        ("roles", "0003_remove_role_user"),
        ("status", "0003_remove_status_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="detailuser",
            name="role",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="roles.role"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="detailuser",
            name="status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="status.status",
            ),
            preserve_default=False,
        ),
    ]
