# Generated by Django 5.0.6 on 2024-07-02 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("status", "0002_status_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="status",
            name="user",
        ),
    ]
